version: '3.8'

services:
  postgres:
    image: 'postgres:16.3-alpine'
    container_name: KnuDevDatabase
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-knudevpass}
      POSTGRES_DB: knudev_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - knudev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address :9090
    ports:
      - '9000:9000'   # MinIO API
      - '9090:9090'   # MinIO Console
    volumes:
      - minio-data:/data
    networks:
      - knudev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knudev-app
    restart: unless-stopped
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: ${DB_URI:-jdbc:postgresql://postgres:5432/knudev_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-knudevpass}

      # MinIO Configuration
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      # Application Configuration
      BASE_URL: http://localhost:5000
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - knudev-network
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:5000/actuator/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

networks:
  knudev-network:
    driver: bridge
