services:
  postgres:
    image: 'postgres:16.3-alpine'
    container_name: KnuDevDatabase
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-knudevpass}
      POSTGRES_DB: knudev_db

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'