server:
  port: 5000
spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/knudev_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:knudevpass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: liquibase
    change-log: classpath:db/master.yaml
  jackson:
    time-zone: Europe/Kiev

logging:
  level:
    org:
      springframework:
        transaction:
          support:
            TransactionSynchronizationUtils: info

application:
  base-url: ${BASE_URL:http://localhost:5000}
  email-verification-token:
    expiration: 60 #60 minutes
  minio:
    url: ${MINIO_URL}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
  jwt:
    issuer: KNUdev
    expiration: 600000 #10 minutes
    refresh-token:
      expiration: 1440000 #24 hours

