server:
  port: 5000
spring:
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/knudev_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:knudevpass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: liquibase
    change-log: classpath:db/master.yaml
  jackson:
    time-zone: Europe/Kiev

logging:
  level:
    org:
      springframework:
        transaction:
          support:
            TransactionSynchronizationUtils: info

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

application:
  baseUrl: ${BASE_URL:http://localhost:5000}
  email_verification_token:
    expiration: 60 #60 minutes
  jwt:
    secret_base64_key: OblBr1u8BlwbqA61vt0yk4TC/mPlvT2O+t2m9SCci6g=
    issuer: KNUdev
    expiration: 600000 #10 minutes
    #    expiration: 3000 #30 seconds
    refresh-token:
      #      expiration: 20000 #30 seconds
      expiration: 1440000 #24 hours
