spring:
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/knudev_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:knudevpass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: liquibase
    change-log: classpath:db/master.yaml
  jackson:
    time-zone: Europe/Kiev

logging:
  level:
    org:
      springframework:
        transaction:
          support:
            TransactionSynchronizationUtils: info

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
baseUrl: ${BASE_URL:http://localhost:5000}
